# Generated by Django 3.2.10 on 2023-08-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_appointmentstatusdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentstatusdb',
            old_name='Name',
            new_name='Patient_Name',
        ),
    ]
