# Generated by Django 3.2.10 on 2023-08-02 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_signup'),
        ('Backend', '0003_rename_name_appointmentstatusdb_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.appointment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.admin')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointmentstatusdb',
        ),
    ]
