# Generated by Django 3.2.10 on 2023-08-02 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
