# Generated by Django 3.2.10 on 2023-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_delete_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField(blank=True, null=True)),
                ('Day', models.CharField(blank=True, max_length=20, null=True)),
                ('Doctor', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
