# Generated by Django 3.2.10 on 2023-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='Day',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
