# Generated by Django 3.2.10 on 2023-08-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_auto_20230802_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='Day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='Time',
            field=models.TimeField(),
        ),
    ]
