# Generated by Django 3.2.10 on 2023-08-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
