# Generated by Django 3.2.10 on 2023-08-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_appointment_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Age',
        ),
    ]
