# Generated by Django 3.2.10 on 2023-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_remove_appointment_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
